name: formjson
description: "Hytte Hub Form Json"
publish_to: "none"
version: 2.0.4+78

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hyttahub:
    path: ../..

  cloud_firestore: ^6.0.2
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  go_router: ^16.2.2
  cloud_functions: ^6.0.2
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  path_provider: ^2.1.5
  hydrated_bloc: ^10.1.1
  file_picker: ^10.3.1
  bloc: ^9.0.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
