name: hyttahub
description: "Package for base flutter app functionality."
version: 0.1.0
# homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  cloud_functions: ^6.0.2
  url_launcher: ^6.3.2
  equatable: ^2.0.7
  protobuf: ^4.2.0
  go_router: ^16.2.2
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  intl: ^0.20.2
  protoc_plugin: ^22.5.0
  get_it: ^8.0.3
  crypto: ^3.0.3
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  fake_cloud_firestore: ^4.0.0
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package

# The following section is specific to Flutter packages.
flutter:
  generate: true
