name: albums
description: "Hytte Hub Albums"
publish_to: 'none'
version: 2.0.4+78

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hyttahub:
    path: ../..

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_bloc: ^9.1.1
  protobuf: ^3.1.0
  get_it: ^8.2.0
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  path_provider: ^2.1.5
  hydrated_bloc: ^10.1.1
  firebase_storage: ^12.4.10
  firebase_core: ^3.15.2
  file_picker: ^10.3.1
  bloc: ^9.0.0
  cloud_functions: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true
